### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by alpern95** [allenan/node-red-contrib-redis-storage#2]
I use a secure redis server
And have a probleme when launching node-red it failed.

I change these settings: 
redis: {
  host: your.redis.host,
  pass: your.redis.password,
  port: your.redis.port
},

with:
redis: {
  host: your.redis.host,
  pass**word**: your.redis.password,
  port: your.redis.port
},

And now its working.
Can you confirm my way and change the README ?

Log:
déc. 26 14:41:12xxxxx systemd[1]: Started Node-RED.
déc. 26 14:41:12 xxxxx systemd[1]: Starting Node-RED...
déc. 26 14:41:12 xxxxx node-red[3118]: 26 Dec 14:41:12 - [red] Uncaught Exception:
déc. 26 14:41:12 xxxxx node-red[3118]: 26 Dec 14:41:12 - ReplyError: Ready check failed: NOAUTH Authentication required.
déc. 26 14:41:12 xxxxx node-red[3118]: at parseError (/root/.node-red/node_modules/redis-parser/lib/parser.js:193:12)
déc. 26 14:41:12 35-xxxxxx node-red[3118]: at parseType (/root/.node-red/node_modules/redis-parser/lib/parser.js:303:14)
déc. 26 14:41:12 xxxxxxx systemd[1]: node-red.service: main process exited, code=exited, status=1/FAILURE

**Comment by allenan** [comment]
thanks, `password` is correct, I've updated the readme 👍
